[features]
seeds = false
[programs.localnet]
agreement = "AzST5p5ATAN1ABdwWXzV7Z8667b3qqA1JUz9w7eWE6Dt"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/mnt/d/Works/Blockchain/Solana/wallets/phantom.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
